# Generated by Django 2.1.1 on 2018-09-14 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('remoteControl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='lastConnected',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='machine',
            name='registered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
