# Generated by Django 2.1.1 on 2018-09-14 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remoteControl', '0003_order_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='machineId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remoteControl.Machine'),
        ),
    ]
