# Generated by Django 2.1.1 on 2018-09-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remoteControl', '0004_auto_20180914_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='silentMode',
            field=models.BooleanField(default=False),
        ),
    ]
